"""Added required tables

Revision ID: 5661fd0d92a5
Revises: 56fe7bd33f4a
Create Date: 2022-09-13 14:48:36.119452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5661fd0d92a5'
down_revision = '56fe7bd33f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
