"""Added required tables

Revision ID: 569d9f60f703
Revises: bdd0e0d8e81a
Create Date: 2022-09-13 21:25:44.114819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569d9f60f703'
down_revision = 'bdd0e0d8e81a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
