"""Added required tables

Revision ID: 56fe7bd33f4a
Revises: b9ee71c37242
Create Date: 2022-09-13 14:47:09.542803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fe7bd33f4a'
down_revision = 'b9ee71c37242'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
