"""Added required tables

Revision ID: 79b4c950068b
Revises: adede4fc40a2
Create Date: 2022-09-15 11:21:59.896599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b4c950068b'
down_revision = 'adede4fc40a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
