"""Added required tables

Revision ID: adede4fc40a2
Revises: 569d9f60f703
Create Date: 2022-09-13 21:27:58.294343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adede4fc40a2'
down_revision = '569d9f60f703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
