"""Added required tables

Revision ID: bbf3f5c363b2
Revises: cad5cf3c1e1b
Create Date: 2022-09-25 23:30:22.575189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf3f5c363b2'
down_revision = 'cad5cf3c1e1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'region')
    # ### end Alembic commands ###
