"""Added required tables

Revision ID: ecf77031c326
Revises: 79b4c950068b
Create Date: 2022-09-15 12:20:58.819316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf77031c326'
down_revision = '79b4c950068b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
